<a href="https://colab.research.google.com/github/candidobri2/time-tabling/blob/main/Algoritmo_Time_tabling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random as rd
from scipy.optimize import linear_sum_assignment
import time

## Passo 1 - Leitura dos parâmetros

In [ ]:
# UFC/DEMA, 2022.1 - Lab. de Otimizacao (CC0328)

import xml.etree.ElementTree as ET
 
def read_entities(root):
    d = dict()
    for e in root:
        e_from = int(e.get('from'))
        e_to = int(e.get('to'))
        d[e.tag] = {}
        d[e.tag]['from'] = e_from
        d[e.tag]['to'] = e_to
    return d

def read_requirements(root):
    R = []
    
    for e in root:
        d = dict()
        
        c = int(e.get('class'))
        t = int(e.get('teacher'))
        theta = int(e.get('lessons'))
        lambd = int(e.get('max_per_day'))
        mu = int(e.get('double_lessons'))
        R.append((c,t,theta,lambd,mu))

    return R

def read_unavailabilities(root):
    U = []
    
    for e in root:
        d = dict()
        
        t = int(e.get('teacher'))
        d = int(e.get('day'))
        h = int(e.get('period'))
        U.append((t,d,h))

    return U


# Passing the path of the xml document
tree = ET.parse('params_rds.xml')
 
# getting the parent tag of the xml document
root = tree.getroot()

   
assert root.tag == 'file' and root[0].tag == 'data'

for secao in root[0]:
    print(f'Reading {secao.tag}')
    
    if secao.tag == 'entities':
        params = read_entities(secao)
    elif secao.tag == 'requirements':
        R = read_requirements(secao)
    elif secao.tag == 'teacherunavailabilities':
        U = read_unavailabilities(secao)

print(params)
print(R)
print(len(R))
print(U)



Reading entities
Reading requirements
Reading teacherunavailabilities
{'classes': {'from': 0, 'to': 3}, 'teachers': {'from': 0, 'to': 15}, 'days': {'from': 0, 'to': 4}, 'periods': {'from': 0, 'to': 4}}
[(0, 0, 5, 3, 1), (0, 1, 1, 1, 0), (0, 2, 1, 1, 0), (0, 3, 2, 2, 1), (0, 4, 3, 3, 1), (0, 1, 4, 2, 2), (0, 5, 1, 1, 0), (0, 6, 1, 1, 0), (0, 7, 2, 2, 1), (0, 8, 1, 1, 0), (0, 9, 2, 2, 1), (0, 10, 2, 1, 0), (1, 1, 1, 1, 0), (1, 2, 1, 1, 0), (1, 0, 5, 3, 1), (1, 1, 4, 2, 2), (1, 11, 3, 3, 1), (1, 3, 2, 2, 1), (1, 9, 2, 2, 1), (1, 6, 1, 1, 0), (1, 8, 1, 1, 0), (1, 5, 1, 1, 0), (1, 7, 2, 2, 1), (1, 12, 2, 1, 0), (2, 13, 2, 2, 1), (2, 2, 1, 1, 0), (2, 0, 5, 3, 1), (2, 1, 4, 2, 2), (2, 9, 2, 2, 1), (2, 1, 1, 1, 0), (2, 5, 2, 2, 1), (2, 6, 1, 1, 0), (2, 5, 1, 1, 0), (2, 4, 3, 3, 1), (2, 8, 1, 1, 0), (2, 14, 2, 1, 0), (3, 2, 1, 1, 0), (3, 1, 1, 1, 0), (3, 13, 2, 2, 1), (3, 0, 5, 3, 1), (3, 9, 2, 2, 1), (3, 1, 4, 2, 2), (3, 11, 1, 1, 0), (3, 6, 1, 1, 0), (3, 6, 1, 1, 0), (3, 11, 2, 2, 1), (3, 7, 

In [ ]:
###função algoritmo construtivo
def algoritmo_construtivo(U,R,params):
  n_teachers = params["teachers"]["to"]+1
  n_periods =  (params['days']["to"]+1) * (params["periods"]["to"]+1)
  turmas = params["classes"]["to"]+1

  z = np.full(((params["classes"]["to"]+1),(params["days"]["to"]+1)*(params["periods"]["to"]+1)),-1)

  for i in R:
    c = i[0]
    aula_semana = i[2]
    while aula_semana>0:
        a = rd.choice(range((params["days"]["to"]+1)*(params["periods"]["to"]+1)))
        if z[c][a] == -1:
            z[c][a] = R.index(i)
            aula_semana-=1

  return z,n_teachers,n_periods,turmas



In [ ]:
z, n_teachers,n_periods,turmas = algoritmo_construtivo(U,R,params)


In [ ]:
z

array([[ 4,  4, 10,  7,  0,  0,  5,  9,  2, 10, 11,  0,  5,  3,  5,  0,
         8,  8,  3,  5,  0, 11,  4,  1,  6],
       [13, 15, 15, 14, 16, 14, 14, 12, 15, 22, 14, 21, 17, 23, 19, 18,
        18, 16, 22, 16, 14, 15, 20, 23, 17],
       [34, 30, 31, 33, 28, 33, 26, 26, 26, 24, 30, 26, 27, 29, 28, 32,
        35, 35, 27, 27, 25, 27, 33, 26, 24],
       [48, 47, 41, 38, 39, 39, 43, 39, 40, 42, 36, 46, 39, 45, 46, 43,
        45, 40, 41, 38, 39, 41, 48, 41, 37]])

In [ ]:
turmas

4

### Implementando dicionário com indisponibilidades dos professores, convertendo para o indice da coluna para ser usado na HC4


In [ ]:
def dic_indisponibilidade(n_teachers, U):
  ind_dic = {}
  for i in range(n_teachers):
    for u in range(len(U)):
      if i == U[u][0]:
          if U[u][0] not in ind_dic:
            ind_dic[U[u][0]] = [U[u][1]*4+U[u][1]+U[u][2]] 
          else:
            ind_dic[U[u][0]].append(U[u][1]*4+U[u][1]+U[u][2])
  return ind_dic

dic_indisponibilidade = dic_indisponibilidade(n_teachers,U)


## Passo 3 - Implementação do hard constraint 3 - a teacher must teach at most one lesson per period - um professor deve dar apenas uma aula por período.

In [ ]:
def gera_hc3(z,n_teachers,n_periods,turmas,R):
  hc3 = 0
  for t in range(n_teachers):
    for j in range(n_periods):
      cont = 0
      for c in range(turmas):
        index = z[c][j]
        if  R[index][1] == t:
          cont +=1
      if cont > 1:
        hc3 += cont -1
  return hc3

## Passo 4 - Implementação da hard constraint 4 - teachers must not be scheduled to periods in which they are unavailable.  - Os professores não devem ser alocados em períodos em que estão indisponíveis

In [ ]:
def gera_hc4(z,n_teachers,n_periods,turmas,R,dic_indisponibilidade):
  hc4 = 0
  for t in range(n_teachers):
    for j in range(n_periods):
      cont = 0
      for c in range(turmas):
        index = z[c][j]
        if R[index][1] == t and j in dic_indisponibilidade.get(t,[]):
          cont = 1
          break
      hc4 += cont
  return hc4

### Passo 5 - Implementar hard constraint 5 - each requirement r E R, must not have more than y assignements per day - cada requisito não deve ultrapassar o número máximo de aulas por dia 

In [ ]:
def gera_hc5 (z,n_teachers,n_periods,turmas, R):
  hc5 = 0
  for r in R:
    for i in list(np.arange(n_periods).reshape(-1,5)): ###falta generalizar
      n_aulas_dia = 0
      for j in i:
        index = z[r[0]][j]
        if R[index] == r:
          n_aulas_dia +=1
        if n_aulas_dia > r[3]:
          hc5 += n_aulas_dia - r[3]
  return hc5

### Passo 6 - Implementar soft constraint 1 - each requirement r should have at least u double lessons a week - cada requisito deve ter, no mínimo, u aulas duplas na semana

In [ ]:
def gera_sc1(R,z,n_periods,turmas):
  sc1 = 0 
  for r in R:
    aula_dupla = 0
    for c in range(turmas):
      cont = 0
      for j in range(n_periods):
        if R[z[c][j]] == r:
          cont +=1
          if cont == 2:
            aula_dupla +=1
            cont = 0
        else:
          cont = 0
    if aula_dupla < r[2]:
      sc1 += r[2] - aula_dupla
  return sc1




### Passo 7 - Implementar a soft constraint 2 - idle periods in the schedule of teacher should be avoided - períodos ociosos nos horários dos professores devem ser evitados

In [ ]:
def gera_sc2(z,n_teachers,n_periods,turmas,R):
  sc2=0
  for t in range(n_teachers):
    for d in list(np.arange(n_periods).reshape(-1,5)):
      #ntd = 0
      em_uso = []
      for j in d:
        for c in range(turmas):
          if R[z[c][j]][1] == t:
            em_uso.append(j)
      if len(em_uso) >=2:
        sc2 += (em_uso[-1] - em_uso[0] - 1) - (len(em_uso) - 2)
  return sc2

### Passo 8 - Implementar a soft constraint 3 - the teacher's schedule should be concentrated on a minimum number of days - A escala do professor deve se concentrar no menor número de dias

In [ ]:
def gera_sc3(n_teachers,n_periods,turmas,R,z):
  sc3 = 0
  for t in range(n_teachers):
    for d in np.arange(n_periods).reshape(-1,5):
      contador = 0
      for j in d:
        for c in range(turmas):
          if R[z[c][j]][1] == t:
            contador += 1
            if contador == 1:
              sc3+=1
              break
      break
  return sc3

## Transformando os passos anteriores em uma função 

Preciso para os próximos passos no MT, que a função retorne os resultados dos algoritmos das restrições, por isso preciso colocar tudo numa função só passando a matriz Z

In [ ]:
def constraints(R,U,z,n_teachers,n_periods,turmas):  
  hc3 = gera_hc3(z,n_teachers,n_periods,turmas,R)
  hc4 = gera_hc4(z,n_teachers,n_periods,turmas,R,dic_indisponibilidade)
  hc5 = gera_hc5(z,n_teachers,n_periods,turmas, R)
  sc1 = gera_sc1(R,z,n_periods,turmas)
  sc2 = gera_sc2(z,n_teachers,n_periods,turmas,R)
  sc3 = gera_sc3(n_teachers,n_periods,turmas,R,z)
  return hc3,hc4,hc5,sc1,sc2,sc3

## Função-objetivo

In [ ]:
def f(a):
  f = 100000*a[0] + 100000*a[1] + 10000*a[2] + 1*a[3] + 3*a[4] + 9*a[5]
  return f

## Aplicar a solução MT

In [ ]:
print(n_periods)
print(turmas)

25
4


In [ ]:
z.shape

(4, 25)

In [ ]:
a =constraints(R,U,z,n_teachers,n_periods,turmas)

In [ ]:
def mt_operator2(R,U,z,n_teachers,n_periods,turmas):
  a = constraints(R,U,z,n_teachers,n_periods,turmas)  
  g = f(a)
  h = 0
  i = 2*turmas
  while h < g:
    g = f(a)
    while i>0:
      c = rd.choice(range(turmas))
      
      subset_R = rd.sample(range(n_periods),3)
      requisitos = []
      for j in subset_R:
        requisitos.append(z[c][j])
        z[c][j] = -1
      
      mcap = np.empty((0,3),int)
      
      for i in requisitos:
        lista_mcap = []
        
        for h in subset_R:
          z[c][h] = i
          a = constraints(R,U,z,n_teachers,n_periods,turmas)
          f_linha = f(a)
          lista_mcap.append(f_linha)
          z[c][h] = -1
        
        mcap = np.append(mcap, np.array([lista_mcap]),axis=0)
    
      row_ind,col_ind = linear_sum_assignment(mcap)
      for index,local in enumerate(col_ind):
        z[c][subset_R[local]] = requisitos[index]
      i = i -1
    a = constraints(R,U,z,n_teachers,n_periods,turmas)  
    h = f(a)      
  return z

  

    
      

In [ ]:
new_z = mt_operator2(R,U,z,n_teachers,n_periods,turmas)

In [ ]:

new_z

array([[10, 10,  5,  5,  0,  0,  4,  6,  0, 11,  5,  5,  2,  0,  0,  3,
         1,  8,  4,  8,  7,  9,  4,  3, 11],
       [14, 14, 16, 18, 18, 19, 22, 22, 16, 14, 17, 17, 15, 15, 23, 15,
        15, 16, 12, 23, 21, 13, 20, 14, 14],
       [33, 27, 28, 26, 25, 27, 27, 29, 32, 35, 26, 26, 30, 33, 33, 31,
        30, 27, 28, 35, 34, 26, 26, 24, 24],
       [45, 45, 39, 36, 41, 38, 39, 39, 41, 48, 42, 40, 39, 43, 48, 46,
        46, 38, 39, 40, 47, 37, 43, 41, 41]])

In [ ]:
def ils_mt(Z, tempo,n_periods,n_teachers,turmas,R,U):
  #atualizar o valor da matriz Z
  Z_linha = Z
  nao_melhorado = 0
  
  limite = time.time() + tempo
  while time.time() < limite:
    Z = pertubation(Z,2, turmas, n_periods)
    Z = mt_operator2(R,U,Z,n_teachers,n_periods,turmas)
    a_Z = constraints(R,U,Z,n_teachers,n_periods,turmas)
    a_Z_linha = constraints(R,U,Z_linha,n_teachers,n_periods,turmas)
    if f(a_Z) < f(a_Z_linha):
      nao_melhorado = 0
    else:
      nao_melhorado +=1
    if f(a_Z) <= f(a_Z_linha):
      Z = Z_linha
    if nao_melhorado >= 5:
      Z = Z_linha
      nao_melhorado = 0
  obj = constraints(R,U,Z_linha,n_teachers,n_periods,turmas)
  func_obj = f(obj)
  return Z_linha,func_obj

  


In [ ]:
#média do valor da função objetivo
valores = []
for i in range(10):
  matriz,valor_func_obj = ils_mt(z, 100,n_periods,n_teachers,turmas,R,U)
  valores.append(valor_func_obj)
print(sum(valores)/len(valores))


130149.2


In [ ]:
matriz

array([[ 8,  8,  5,  5,  0,  3,  3,  2,  6,  9,  0,  0,  4,  0,  1,  4,
         4,  5,  5, 11,  7,  0, 10, 10, 11],
       [15, 15, 18, 22, 22, 14, 16, 16, 18, 23, 13, 21, 17, 17, 14, 16,
        15, 19, 23, 14, 20, 15, 12, 14, 14],
       [28, 28, 26, 26, 29, 24, 24, 26, 26, 35, 31, 33, 27, 27, 35, 30,
        30, 33, 26, 27, 33, 32, 34, 27, 25],
       [39, 39, 46, 40, 40, 41, 41, 43, 45, 48, 41, 41, 39, 45, 38, 46,
        36, 39, 43, 38, 42, 37, 39, 47, 48]])

In [ ]:
def pertubation(z, dias, turmas,n_periods):
    indices = [0,5,10,15,20]
    dic_id = {0:[0,1,2,3,4], 5:[5,6,7,8,9],10:[10,11,12,13,14],15:[15,16,17,18,19], 20:[20,21,22,23,24]}
    # escolher dois desses dias aleatoriamente e colocar mais 5
    dias = rd.sample(indices,k=dias)
    linha_aleatoria = rd.choice(range(turmas))
    req_sorteado = z[linha_aleatoria][dias[0]]

    t = R[req_sorteado][1]

    for c in range(turmas):
      D = [j for i in dias for j in dic_id]
      for k in D:
        if R[z[c][k]][1] == t:
          if k<24:
            z[c][k],z[c][k+1] = z[c][k+1],z[c][k]
          if k==24:
            z[c][k],z[c][k-1] = z[c][k-1],z[c][k]
    
    return z

      





### Experimentos

In [ ]:
z_ils = ils_mt(new_z,100,n_periods,n_teachers, turmas, R,U)

In [ ]:
z_ils

array([[10, 10,  5,  5,  0,  0,  4,  6,  0, 11,  5,  5,  2,  0,  0,  3,
         1,  8,  4,  8,  7,  9,  4,  3, 11],
       [14, 14, 16, 18, 18, 19, 22, 22, 16, 14, 17, 17, 15, 15, 23, 15,
        15, 16, 12, 23, 21, 13, 20, 14, 14],
       [33, 27, 28, 26, 25, 27, 27, 29, 32, 35, 26, 26, 30, 33, 33, 31,
        30, 27, 28, 35, 34, 26, 26, 24, 24],
       [45, 45, 39, 36, 41, 38, 39, 39, 41, 48, 42, 40, 39, 43, 48, 46,
        46, 38, 39, 40, 47, 37, 43, 41, 41]])

In [ ]:
ils = constraints(R,U,z_ils,n_teachers,n_periods,turmas)

In [ ]:
f(construtivo)

2730165

In [ ]:
f(mt)

2530168

In [ ]:
f(ils)

152

In [ ]:
horario_atual = np.array([[0,0,1,2,11,3,3,4,4,4,5,5,6,7,0,8,8,0,0,11,9,10,10,5,5],
                         [12,13,14,15,15,14,14,16,17,17,14,14,15,15,23,18,18,16,16,23,19,20,21,22,22],
                         [24,24,25,26,35,27,27,28,28,29,30,30,31,32,35,26,26,27,27,26,26,33,34,33,33],
                         [36,37,38,38,39,40,40,41,41,42,43,44,39,39,48,45,45,46,46,48,41,41,39,39,47]])

In [ ]:
atual = constraints(R,U,z_ils,n_teachers,n_periods,turmas)

In [ ]:
f(atual)

200117

In [ ]:
atual

(1, 1, 0, 78, 1, 4)

In [ ]:
f(ils)

152

In [ ]:
ils

(0, 0, 0, 80, 6, 6)

In [ ]:
z_ils

array([[ 8,  8,  5,  5,  0,  3,  3,  2,  6,  9,  0,  0,  4,  0,  1,  4,
         4,  5,  5, 11,  7,  0, 10, 10, 11],
       [15, 15, 18, 22, 22, 14, 16, 16, 18, 23, 13, 21, 17, 17, 14, 16,
        15, 19, 23, 14, 20, 15, 12, 14, 14],
       [28, 28, 26, 26, 29, 24, 24, 26, 26, 35, 31, 33, 27, 27, 35, 30,
        30, 33, 26, 27, 33, 32, 34, 27, 25],
       [39, 39, 46, 40, 40, 41, 41, 43, 45, 48, 41, 41, 39, 45, 38, 46,
        36, 39, 43, 38, 42, 37, 39, 47, 48]])